import { NotificationItemData } from './NotificationItem';

export const INITIAL_NOTIFICATIONS: NotificationItemData[] = [
  {
    id: '1',
    type: 'job',
    titleUz: 'Yangi ish o\'rni!',
    titleRu: 'Новая вакансия!',
    titleEn: 'New Job Opportunity!',
    descUz: '"Tashkent City" qurilish ob\'ektida g\'isht teruvchi mutaxassis kerak. Maosh: 5,000,000 so\'m/oy.',
    descRu: 'Требуется каменщик на строительный объект "Tashkent City". Зарплата: 5 000 000 сум/мес.',
    descEn: 'Bricklayer needed at "Tashkent City" construction site. Salary: 5,000,000 UZS/month.',
    timeUz: '14:20',
    timeRu: '14:20',
    timeEn: '2:20 PM',
    isUnread: true,
    group: 'today'
  },
  {
    id: '2',
    type: 'apply',
    titleUz: 'Arizangiz qabul qilindi',
    titleRu: 'Заявка принята',
    titleEn: 'Application Received',
    descUz: '"Santexnik" lavozimi uchun yuborgan arizangiz ish beruvchi tomonidan ko\'rib chiqilmoqda.',
    descRu: 'Ваша заявка на вакансию "Сантехник" находится на рассмотрении у работодателя.',
    descEn: 'Your application for "Plumber" is being reviewed by the employer.',
    timeUz: '10:05',
    timeRu: '10:05',
    timeEn: '10:05 AM',
    isUnread: true,
    group: 'today'
  },
  {
    id: '3',
    type: 'message',
    titleUz: 'Yangi xabar',
    titleRu: 'Новое сообщение',
    titleEn: 'New Message',
    descUz: 'Ish beruvchi "Artel" sizga intervyu vaqti haqida xabar yubordi.',
    descRu: 'Работодатель "Artel" отправил вам сообщение о времени собеседования.',
    descEn: 'Employer "Artel" sent you a message about the interview time.',
    timeUz: 'Kecha, 18:45',
    timeRu: 'Вчера, 18:45',
    timeEn: 'Yesterday, 6:45 PM',
    isUnread: false,
    group: 'yesterday'
  },
  {
    id: '4',
    type: 'profile',
    titleUz: 'Profilni to\'ldiring',
    titleRu: 'Заполните профиль',
    titleEn: 'Complete Profile',
    descUz: 'Iltimos, ish tajribangiz haqidagi ma\'lumotlarni to\'ldiring, bu ish topish imkoniyatini 40% ga oshiradi.',
    descRu: 'Пожалуйста, заполните информацию о вашем опыте работы, это увеличит шансы найти работу на 40%.',
    descEn: 'Please fill in your work experience, this increases your chances of finding a job by 40%.',
    timeUz: 'Kecha, 09:12',
    timeRu: 'Вчера, 09:12',
    timeEn: 'Yesterday, 9:12 AM',
    isUnread: false,
    group: 'yesterday'
  },
  {
    id: '5',
    type: 'system',
    titleUz: 'Tizim yangilanishi',
    titleRu: 'Обновление системы',
    titleEn: 'System Update',
    descUz: 'Ilova yangilandi. Endi xaritalar yanada tezroq ishlaydi.',
    descRu: 'Приложение обновлено. Теперь карты работают еще быстрее.',
    descEn: 'The app has been updated. Maps are now even faster.',
    timeUz: 'Kecha, 02:00',
    timeRu: 'Вчера, 02:00',
    timeEn: 'Yesterday, 2:00 AM',
    isUnread: false,
    group: 'yesterday'
  }
];

export const getNotificationTranslations = (language: 'uz' | 'ru' | 'en') => ({
  uz: {
    title: 'Bildirishnomalar',
    today: 'Bugun',
    yesterday: 'Kecha',
    allRead: "Barchasi o'qildi",
    markAllAsRead: "Hammasini o'qilgan qilish",
    noNoti: 'Bildirishnomalar mavjud emas',
    filterCategory: 'Kategoriyalar',
    catAll: 'Barchasi',
    catUnread: "O'qilmaganlar",
    catJob: "Ish takliflari",
    catApply: 'Arizalar',
    catMessage: 'Xabarlar',
    catSystem: 'Tizim va profil',
    openChat: "Chatga o'tish",
    viewDetails: "Tafsilotlarni ko'rish",
    badgeJob: 'Ish',
    badgeApply: 'Ariza',
    badgeMessage: 'Xabar',
    badgeProfile: 'Profil',
    badgeSystem: 'Tizim'
  },
  ru: {
    title: 'Уведомления',
    today: 'Сегодня',
    yesterday: 'Вчера',
    allRead: 'Все прочитано',
    markAllAsRead: 'Отметить все как прочитанные',
    noNoti: 'Уведомлений пока нет',
    filterCategory: 'Категории',
    catAll: 'Все',
    catUnread: 'Непрочитанные',
    catJob: 'Вакансии',
    catApply: 'Заявки',
    catMessage: 'Сообщения',
    catSystem: 'Система и профиль',
    openChat: 'Перейти в чат',
    viewDetails: 'Подробнее',
    badgeJob: 'Работа',
    badgeApply: 'Заявка',
    badgeMessage: 'Сообщение',
    badgeProfile: 'Профиль',
    badgeSystem: 'Система'
  },
  en: {
    title: 'Notifications',
    today: 'Today',
    yesterday: 'Yesterday',
    allRead: 'All read',
    markAllAsRead: 'Mark all as read',
    noNoti: 'No notifications yet',
    filterCategory: 'Categories',
    catAll: 'All',
    catUnread: 'Unread',
    catJob: 'Jobs',
    catApply: 'Applications',
    catMessage: 'Messages',
    catSystem: 'System & Profile',
    openChat: 'Open Chat',
    viewDetails: 'View Details',
    badgeJob: 'Job',
    badgeApply: 'Apply',
    badgeMessage: 'Message',
    badgeProfile: 'Profile',
    badgeSystem: 'System'
  }
}[language]);
