export const LANDING_TEXTS = {
  uz: {
    heroBadge: "O'zbekistondagi #1 Kunlik Ishlar va Smenalar Platformasi",
    heroTitleLine1: "Kunlik daromad va",
    heroTitleLine2: "ishonchli xodimlarni toping",
    heroSubtitle: "Baito — xaritadan yoningizdagi soatlik va kunlik ishlarni topish, smena yakunlanishi bilan maosh olish hamda 15 daqiqada tasdiqlangan xodimlarni yollash xizmati.",
    workerBtn: "Ishchi sifatida boshlash",
    employerBtn: "Ish beruvchi bo'lib kirish",
    mapBtn: "Xaritadan ish izlash",
    stat1: "15,000+",
    stat1Label: "Aktiv e'lonlar",
    stat2: "98.4%",
    stat2Label: "Ijobiy fikrlar",
    stat3: "15 daqiqa",
    stat3Label: "O'rtacha yollash vaqti",
    ticker: "Bugun Toshkent va viloyatlarda 450+ yangi smena e'lon qilindi!",
    calcTitle: "Qancha daromad topishingiz mumkin?",
    calcSubtitle: "Soha va kunlik ish soatingizni tanlang, taxminiy oylik daromadni hisoblang",
    catTitle: "Ommabop yo'nalishlar",
    catSubtitle: "Har kungi soatlik va kunlik mos smenani tanlang",
    rolesTitle: "Har bir foydalanuvchi uchun qulay imkoniyat",
    rolesSubtitle: "Platformamiz ish izlovchi va tashkilotlarni bir zumda bog'laydi",
    mapTitle: "Xarita bo'yicha Smenalar",
    mapSubtitle: "Toshkent va viloyatlardagi eng yaqin bo'sh ishlarni xaritadan ko'ring",
    howTitle: "Platforma qanday ishlaydi?",
    howSubtitle: "Ish izlovchilar va ish beruvchilar uchun 4 ta oddiy qadam",
    faqTitle: "Ko'p beriladigan savollar",
    reviewsTitle: "Foydalanuvchilarimiz natijalari"
  },
  ru: {
    heroBadge: "#1 Платформа подработок и смен в Узбекистане",
    heroTitleLine1: "Быстрый ежедневный доход и",
    heroTitleLine2: "надежные сотрудники",
    heroSubtitle: "Baito — поиск почасовых смен на карте, гарантированные выплаты после работы и подбор проверенного персонала за 15 минут.",
    workerBtn: "Начать как соискатель",
    employerBtn: "Разместить вакансию",
    mapBtn: "Поиск работы на карте",
    stat1: "15,000+",
    stat1Label: "Активных вакансий",
    stat2: "98.4%",
    stat2Label: "Положительных отзывов",
    stat3: "15 минут",
    stat3Label: "Среднее время найма",
    ticker: "Сегодня опубликовано более 450 новых смен по Узбекистану!",
    calcTitle: "Сколько вы можете заработать?",
    calcSubtitle: "Выберите сферу и часы работы, чтобы рассчитать примерный доход",
    catTitle: "Популярные категории",
    catSubtitle: "Выберите подходящую смену с ежедневной оплатой",
    rolesTitle: "Удобные возможности для каждого",
    rolesSubtitle: "Платформа Baito объединяет соискателей и работодателей за минуты",
    mapTitle: "Смены на живой карте",
    mapSubtitle: "Смотрите ближайшие вакансии в Ташкенте и регионах",
    howTitle: "Как работает платформа?",
    howSubtitle: "4 простых шага для работников и работодателей",
    faqTitle: "Часто задаваемые вопросы",
    reviewsTitle: "Отзывы и результаты"
  },
  en: {
    heroBadge: "#1 Daily Shift & Hourly Work Platform in Uzbekistan",
    heroTitleLine1: "Instant daily earnings &",
    heroTitleLine2: "reliable staff hiring",
    heroSubtitle: "Baito connects you with nearby hourly jobs on an interactive map, guarantees instant payouts upon shift end, and helps businesses hire staff in 15 minutes.",
    workerBtn: "Start as Worker",
    employerBtn: "Post a Job",
    mapBtn: "Explore Map Jobs",
    stat1: "15,000+",
    stat1Label: "Active Job Offers",
    stat2: "98.4%",
    stat2Label: "Satisfaction Rate",
    stat3: "15 mins",
    stat3Label: "Avg Hiring Speed",
    ticker: "Over 450+ new daily shifts posted today across Uzbekistan!",
    calcTitle: "How much can you earn?",
    calcSubtitle: "Select your category and working hours to estimate your monthly earnings",
    catTitle: "Popular Categories",
    catSubtitle: "Choose flexible hourly shifts that fit your schedule",
    rolesTitle: "Tailored Experience for Everyone",
    rolesSubtitle: "Seamlessly connecting job seekers with businesses instantly",
    mapTitle: "Live Interactive Map Shifts",
    mapSubtitle: "Explore nearby shifts across Tashkent and major regions",
    howTitle: "How Platform Works",
    howSubtitle: "4 effortless steps for both job seekers and hiring managers",
    faqTitle: "Frequently Asked Questions",
    reviewsTitle: "Real stories from our community"
  }
};

export const MOCK_LIVE_SHIFTS = [
  {
    id: 'real-1',
    titleUz: 'Kuryer (Piyoda / Velosiped)',
    titleRu: 'Курьер (Пеший / Вело)',
    company: 'Express Delivery Tashkent',
    district: 'Chilonzor, 9-mavze',
    pay: '280,000 so\'m/smena',
    payNum: 280000,
    time: '10:00 - 18:00 (8 soat)',
    category: 'courier',
    lat: 41.2856,
    lng: 69.2034,
    badge: 'Bugun',
    urgent: true,
    descriptionUz: "Belgilangan hududda kichik o'lchamdagi buyurtmalar va xat-xabarlarni mijozlarga o'z vaqtida va xavfsiz yetkazib berish.",
    descriptionRu: "Своевременная и безопасная доставка небольших заказов и корреспонденции клиентам в пределах указанного района.",
    perksUz: ["⚡ Kunlik to'lov", "🚴 Transport ta'minlanadi", "🍲 Tushlik binosida"]
  },
  {
    id: 'real-2',
    titleUz: 'Supermarket Kassiri',
    titleRu: 'Кассир супермаркета',
    company: 'Korzinka.uz',
    district: 'Mirzo Ulug\'bek, Buyuk Ipak Yoli',
    pay: '250,000 so\'m/smena',
    payNum: 250000,
    time: '08:00 - 16:00 (8 soat)',
    category: 'sales',
    lat: 41.3280,
    lng: 69.3320,
    badge: 'Bugun',
    urgent: false,
    descriptionUz: "Xaridorlarga xizmat ko'rsatish, kassa apparati bilan ishlash, to'lovlarni naqd va plastik karta orqali qabul qilish.",
    descriptionRu: "Обслуживание покупателей, работа с кассовым аппаратом, прием оплаты наличными и банковскими картами.",
    perksUz: ["💳 Kunlik maosh", "👔 Maxsus kiyim", "🎓 Bepul o'rgatiladi"]
  },
  {
    id: 'real-3',
    titleUz: 'Ofitsiant (Kechki smena)',
    titleRu: 'Официант (Вечерняя смена)',
    company: 'Yulduz Restorani',
    district: 'Yunusobod, Mega Planet',
    pay: '320,000 so\'m/smena',
    payNum: 320000,
    time: '17:00 - 01:00 (8 soat)',
    category: 'resto',
    lat: 41.3642,
    lng: 69.2872,
    badge: 'Bugun',
    urgent: true,
    descriptionUz: "Mehmonlarni kutib olish, taomlar va ichimliklar menyusi bo'yicha maslahat berish, buyurtmalarni chaqqon yetkazish.",
    descriptionRu: "Встреча гостей, консультация по меню блюд и напитков, быстрое и вежливое обслуживание столов.",
    perksUz: ["💰 Choychaqa (Tips)", "🚖 Tungi taksi kompensatsiya", "🍲 Bepul kechki ovqat"]
  },
  {
    id: 'real-4',
    titleUz: 'Omborxona saralovchisi',
    titleRu: 'Сортировщик склада',
    company: 'Texnomart Ombori',
    district: 'Sergeli, Sanoat Zonasi',
    pay: '350,000 so\'m/smena',
    payNum: 350000,
    time: '09:00 - 18:00 (9 soat)',
    category: 'warehouse',
    lat: 41.2215,
    lng: 69.2180,
    badge: 'Ertaga',
    urgent: false,
    descriptionUz: "Maishiy texnika va tovarlarni qabul qilish, joy-joyiga saralash, qadoqlash hamda jo'natishga tayyorlash.",
    descriptionRu: "Прием бытовой техники и товаров, сортировка по стеллажам, упаковка и подготовка к отправке.",
    perksUz: ["📦 Qulay sharoit", "☕ Bepul kofe/choy", "🤝 Inoq jamoa"]
  },
  {
    id: 'real-5',
    titleUz: 'Barista Yordamchisi',
    titleRu: 'Помощник бариста',
    company: 'Safia Bakery & Cafe',
    district: 'Yakkasaroy, Shota Rustaveli',
    pay: '220,000 so\'m/smena',
    payNum: 220000,
    time: '08:00 - 16:00 (8 soat)',
    category: 'resto',
    lat: 41.2800,
    lng: 69.2500,
    badge: 'Bugun',
    urgent: false,
    descriptionUz: "Kofe va ichimliklarni tayyorlashda yordam berish, shirinliklar vitrinasini tartibga keltirish, ish joyi ozodaligini saqlash.",
    descriptionRu: "Помощь в приготовлении кофе и напитков, поддержание порядка на витрине десертов и в рабочей зоне.",
    perksUz: ["☕ Bepul kofe & shirinlik", "🌸 Shinam atmosfera", "🎓 Barista ko'nikmalari"]
  },
  {
    id: 'real-6',
    titleUz: 'Avtomoyka mutaxassisi',
    titleRu: 'Автомойщик',
    company: 'Crystal Car Wash',
    district: 'Shayxontohur, Samarqand Darvoza',
    pay: '300,000 so\'m/smena',
    payNum: 300000,
    time: '09:00 - 19:00 (10 soat)',
    category: 'service',
    lat: 41.3100,
    lng: 69.2200,
    badge: 'Tezkor',
    urgent: true,
    descriptionUz: "Avtomobillarni sirtqi va salondan tozalash, kimyoviy ishlov berish va sifatli yuvish ishlarini bajarish.",
    descriptionRu: "Качественная наружная мойка и чистка салона автомобилей с использованием профессиональной химии.",
    perksUz: ["💦 Zamonaviy uskunalar", "💸 Ish hajmidan bonus", "🍲 Issiq tushlik"]
  }
];

export const FAQ_ITEMS = [
  {
    qUz: "Baito platformasi orqali maosh qachon to'lanadi?",
    qRu: "Когда выплачивается зарплата на Baito?",
    aUz: "Smena tugashi bilan ish beruvchi topshiriq bajarilganini tasdiqlaydi va pul mablag'lari darhol bankingiz kartasiga o'tkaziladi.",
    aRu: "Сразу после окончания смены работодатель подтверждает выполнение работы, и деньги моментально поступают на вашу карту."
  },
  {
    qUz: "Ishchilar va Ish beruvchilar qanday va qaysi mezon bilan tekshiriladi?",
    qRu: "Как проверяются работники и работодатели?",
    aUz: "Har bir foydalanuvchi pasport/ID verification bosqichidan o'tadi. Har bir smena yakunida ikki tomonlama shaffof reyting tizimi mavjud.",
    aRu: "Каждый пользователь проходит верификацию по паспорту/ID. После каждой смены действует двусторонняя система рейтинга."
  },
  {
    qUz: "E'lon berish qancha turadi?",
    qRu: "Сколько стоит размещение объявления?",
    aUz: "Ish beruvchilar uchun dastlabki 3 ta e'lon mutlaqo bepul. Keyinchalik ham juda qulay tariflar amal qiladi.",
    aRu: "Для работодателей первые 3 объявления абсолютно бесплатны. Далее действуют выгодные пакеты подписки."
  },
  {
    qUz: "Keng tarqalgan sohalar qaysilar?",
    qRu: "Какие сферы наиболее популярны?",
    aUz: "Kuryerlik, Restoran/Kafe xizmati, Omborxona va Logistika, Qurilish va Tozalash xizmatlari eng yuqori talabga ega.",
    aRu: "Курьерская доставка, общепит, складская логистика, ремонт и клининг пользуются наибольшим спросом."
  }
];

export const JOB_CATEGORIES = [
  { id: 'courier', nameUz: 'Kuryerlik', nameRu: 'Доставка', nameEn: 'Courier & Delivery', count: '1,240+', rate: '180,000 - 350,000 so\'m/kun', iconName: 'Truck' },
  { id: 'resto', nameUz: 'Restoran & Kafe', nameRu: 'Рестораны и общепит', nameEn: 'Resto & Catering', count: '980+', rate: '150,000 - 280,000 so\'m/kun', iconName: 'Utensils' },
  { id: 'warehouse', nameUz: 'Omborxona & Logistika', nameRu: 'Склад и логистика', nameEn: 'Warehouse & Logistics', count: '1,510+', rate: '200,000 - 400,000 so\'m/kun', iconName: 'Package' },
  { id: 'construction', nameUz: 'Qurilish & Tamirlash', nameRu: 'Строительство и ремонт', nameEn: 'Construction & Repair', count: '2,100+', rate: '250,000 - 600,000 so\'m/kun', iconName: 'HardHat' },
  { id: 'promo', nameUz: 'Savdo & Promouter', nameRu: 'Продажи и промоутер', nameEn: 'Sales & Promo', count: '640+', rate: '140,000 - 250,000 so\'m/kun', iconName: 'ShoppingBag' },
  { id: 'cleaning', nameUz: 'Tozalash & Xizmat', nameRu: 'Уборка и сервис', nameEn: 'Cleaning & Service', count: '820+', rate: '160,000 - 300,000 so\'m/kun', iconName: 'Sparkles' }
];
