
FROM python:3.11-alpine

# Install PostgreSQL client, bash & gzip
RUN apk add --no-cache postgresql-client bash gzip

WORKDIR /app

COPY scripts/requirements-bot.txt .
RUN pip install --no-cache-dir -r requirements-bot.txt

COPY scripts/backup_bot.py .

CMD ["python", "backup_bot.py"]
