export const getProfileTranslations = (language: string) => {
  const t = {
    uz: {
      profileTitle: 'Mening profilim',
      workerRole: 'Professional Ishchi',
      employerRole: 'Ish Beruvchi',
      jobs: 'Ishlar',
      rating: 'Reyting',
      badges: 'Nishonlar',
      walletTitle: 'Hamyon balansi',
      walletBtn: 'Yechib olish →',
      verifyTitle: 'Shaxsni tasdiqlash',
      verifyDesc: "Ish o'rinlariga ariza topshirishni boshlash uchun ID hujjatlaringizni ro'yxatdan o'tkazing.",
      verifyBtn: 'Holatni tekshirish',
      verified: 'Hujjatlar tekshirilmoqda',
      verifiedDesc: 'ID hujjatlaringiz moderatsiya navbatida kutilmoqda.',
      editProfile: 'Profilni tahrirlash',
      saveProfile: 'Saqlash',
      share: 'Ulashish',
      pastJobs: "O'tgan ishlar",
      reviews: 'Reytinglar va sharhlar',
      badgesList: 'Nishonlar va malakalar',
      earnings: 'Daromadlar tarixi',
      taxes: 'Soliq hujjatlari',
      notifySettings: 'Xabarlar va bildirishnomalar',
      appSettings: 'Ilova sozlamalari',
      terms: 'Foydalanish shartlari',
      privacy: 'Maxfiylik siyosati',
      about: 'Ilova haqida',
      logout: 'Tizimdan chiqish',
      logoutSuccess: 'Tizimdan muvaffaqiyatli chiqdingiz',
      copied: 'Havola buferga nusxalandi!',
      withdrawPrompt: "Yechib olish uchun summa kiriting (so'm)",
      withdrawSuccessMsg: 'Muvaffaqiyatli yuborildi! Pul 24 soat ichida kartangizga tushadi.',
      requiredFields: "Ism va familiya bo'sh bo'lishi mumkin emas!",
      savedSuccess: "Profil o'zgarishlari saqlandi!",
      demoDesc: "Ushbu profil ma'lumotlari Baito platformasida faoliyatingizni kuzatish uchun xizmat qiladi.",
      vigo: 'VIGO v1.0.0',
      activitySec: 'Ish faoliyati',
      settingsSec: 'Sozlamalar',
      helpSec: 'Yordam',
      cancel: 'Bekor qilish'
    },
    ru: {
      profileTitle: 'Мой профиль',
      workerRole: 'Профессиональный Работник',
      employerRole: 'Работодатель',
      jobs: 'Работы',
      rating: 'Рейтинг',
      badges: 'Значки',
      walletTitle: 'Баланс кошелька',
      walletBtn: 'Вывести →',
      verifyTitle: 'Верификация личности',
      verifyDesc: 'Зарегистрируйте свои ID-документы, чтобы начать подавать заявки на вакансии.',
      verifyBtn: 'Проверить статус',
      verified: 'Документы проверяются',
      verifiedDesc: 'Ваши ID-документы находятся в очереди модерации.',
      editProfile: 'Редактировать профиль',
      saveProfile: 'Сохранить',
      share: 'Поделиться',
      pastJobs: 'Прошлые работы',
      reviews: 'Рейтинги и отзывы',
      badgesList: 'Значки и квалификации',
      earnings: 'История доходов',
      taxes: 'Налоговые документы',
      notifySettings: 'Сообщения и уведомления',
      appSettings: 'Настройки приложения',
      terms: 'Условия использования',
      privacy: 'Политика конфиденциальности',
      about: 'О приложении',
      logout: 'Выйти из системы',
      logoutSuccess: 'Вы успешно вышли из системы',
      copied: 'Ссылка скопирована в буфер обмена!',
      withdrawPrompt: 'Введите сумму для вывода (сум)',
      withdrawSuccessMsg: 'Успешно отправлено! Деньги поступят на вашу карту в течение 24 часов.',
      requiredFields: 'Имя и фамилия не могут быть пустыми!',
      savedSuccess: 'Изменения профиля сохранены!',
      demoDesc: 'Данные профиля служат для отслеживания вашей активности на платформе Baito.',
      vigo: 'VIGO v1.0.0',
      activitySec: 'Деятельность',
      settingsSec: 'Настройки',
      helpSec: 'Помощь',
      cancel: 'Отмена'
    },
    en: {
      profileTitle: 'My Profile',
      workerRole: 'Professional Worker',
      employerRole: 'Employer',
      jobs: 'Jobs',
      rating: 'Rating',
      badges: 'Badges',
      walletTitle: 'Wallet Balance',
      walletBtn: 'Withdraw →',
      verifyTitle: 'Identity Verification',
      verifyDesc: 'Register your ID documents to start applying for high-paying daily jobs.',
      verifyBtn: 'Check Status',
      verified: 'Documents Under Review',
      verifiedDesc: 'Your ID documents are currently in the moderation queue.',
      editProfile: 'Edit Profile',
      saveProfile: 'Save',
      share: 'Share',
      pastJobs: 'Past Jobs',
      reviews: 'Ratings & Reviews',
      badgesList: 'Badges & Qualifications',
      earnings: 'Earnings History',
      taxes: 'Tax Documents',
      notifySettings: 'Messages & Notifications',
      appSettings: 'App Settings',
      terms: 'Terms of Service',
      privacy: 'Privacy Policy',
      about: 'About App',
      logout: 'Log Out',
      logoutSuccess: 'Successfully logged out',
      copied: 'Profile link copied to clipboard!',
      withdrawPrompt: 'Enter amount to withdraw (UZS)',
      withdrawSuccessMsg: 'Request submitted! Money will be credited to your card within 24 hours.',
      requiredFields: 'First and last name cannot be empty!',
      savedSuccess: 'Profile updated successfully!',
      demoDesc: 'This profile data serves to track your professional performance on Baito.',
      vigo: 'VIGO v1.0.0',
      activitySec: 'Work Activity',
      settingsSec: 'Settings',
      helpSec: 'Help',
      cancel: 'Cancel'
    }
  };

  return t[language as 'uz' | 'ru' | 'en'] || t.uz;
};
