export const LOCAL_TEXTS = {
  uz: {
    regTitle: "Ro'yxatdan o'tish",
    loginTitle: "Tizimga kirish",
    roleQuestion: "Kim sifatida davom etasiz?",
    roleSubtitle: "Rolingizni tanlang, keyin o'zgartirib bo'lmaydi",
    ishchi: "Ishchi",
    ishchiDesc: "Ish qidirish, rezyume yaratish va bo'sh ish o'rinlariga ariza topshirish uchun.",
    ishBeruvchi: "Ish beruvchi",
    ishBeruvchiDesc: "E'lonlar joylashtirish, munosib xodimlarni topish va ish jarayonini boshqarish uchun.",
    disclaimer: "Siz bitta hisob bilan bir vaqtda ham ishchi, ham ish beruvchi bo'la olmaysiz.",
    davomEtish: "Davom etish",
    hasAccount: "Hisobingiz bormi?",
    noAccount: "Hisobingiz yo'qmi?",
    adminConnect: "Admin bilan bog'lanish",
    
    // Step 1 Profile Info
    profileInfoTitle: "Profil ma'lumotlari",
    profileInfoSubtitle: "Asosiy ma'lumotlaringizni kiriting",
    step1: "Profil",
    step2: "Hujjatlar",
    step3: "Yakunlash",
    uploadPhoto: "Profil rasm (ixtiyoriy)",
    name: "ISM *",
    surname: "FAMILIYA *",
    birthdate: "TUG'ILGAN SANA *",
    day: "Kun",
    month: "Oy",
    year: "Yil",
    gender: "JINSI *",
    male: "Erkak",
    female: "Ayol",
    email: "EMAIL (IXTIYORIY)",

    // Step 2 Documents
    docTitle: "Hujjatlarni yuklash",
    docSubtitle: "Shaxsingiz va kasbiy ma'lumotingizni tasdiqlang",
    docWorkerPassport: "Pasport yoki ID-karta nusxasi *",
    docWorkerPassportDesc: "Rasm (JPG, PNG) yoki PDF formatda yuklang",
    docWorkerResume: "Rezyume (CV) (ixtiyoriy)",
    docWorkerResumeDesc: "Eski rezyume yoki batafsil ma'lumotnoma",
    docEmployerLicense: "Tashkilot litsenziyasi / Guvohnomasi *",
    docEmployerLicenseDesc: "Tadbirkorlik faoliyati ruxsatnomasi",
    docEmployerLogo: "Tashkilot logotipi (ixtiyoriy)",
    docEmployerLogoDesc: "Brendingiz uchun rasmiy logotip",
    uploadBtn: "Fayl yuklash",
    uploaded: "Yuklandi",
    dragDropText: "Faylni tanlang yoki shu yerga sudrab tashlang",
    demoDocText: "Namuna fayl bilan to'ldirish",
    
    // Custom High-Fidelity Step 2 Keys
    identityTitle: "Shaxsni tasdiqlash",
    identitySubtitle: "Passport ma'lumotlaringizni kiriting. Barcha ma'lumotlar himoyalangan.",
    series: "Seriya",
    passportNumber: "Passport raqami",
    jshshir: "JSHSHIR (14 raqam)",
    passportFront: "Old tomon *",
    passportBack: "Orqa tomon *",
    selfie: "Selfie rasm *",
    selfieSubtitle: "To'g'ridan, aniq, yuz ko'rinib tursin",
    sslNotice: "Barcha hujjatlar SSL shifrlash bilan himoyalangan.",
    employerTitle: "Tashkilotni tasdiqlash",
    employerSubtitle: "Yuridik shaxs ma'lumotlarini kiriting. Barcha ma'lumotlar himoyalangan.",
    orgName: "Tashkilot nomi *",
    stir: "STIR (9 raqam) *",
    license: "Litsenziya / Guvohnoma *",
    logo: "Tashkilot logotipi (ixtiyoriy)",
    submitVerify: "Tasdiqlash va davom etish",

    // Step 3 Finish
    finishTitle: "Hisobni faollashtirish",
    finishSubtitle: "Tizimga kirish uchun maxfiy ma'lumotlarni sozlashingiz so'raladi",
    finishPhone: "TELEFON RAQAM *",
    finishPassword: "PAROL YARATING *",
    finishConfirmPassword: "PAROLNI TASDIQLANG *",
    finishAgree: "Foydalanish shartlari va maxfiylik siyosatiga roziman",
    errorPasswordMatch: "Parollar mos kelmadi",
    errorTerms: "Iltimos, foydalanish shartlarini qabul qiling",
    finishSuccess: "Muvaffaqiyatli ro'yxatdan o'tdingiz!",
    finishButton: "Yakunlash va kirish",
    
    // Login Screen
    phoneLabel: "TELEFON RAQAM *",
    passwordLabel: "PAROL *",
    loginBtn: "Kirish",
    errorRequired: "Iltimos, barcha majburiy maydonlarni to'ldiring",
    phonePlaceholder: "+998 (90) 123-45-67",
    passwordPlaceholder: "Parolingizni kiriting"
  },
  ru: {
    regTitle: "Регистрация",
    loginTitle: "Вход в систему",
    roleQuestion: "В качестве кого вы продолжите?",
    roleSubtitle: "Выберите вашу роль, позже её нельзя будет изменить",
    ishchi: "Соискатель",
    ishchiDesc: "Для поиска работы, создания резюме и отклика на вакансии.",
    ishBeruvchi: "Работодатель",
    ishBeruvchiDesc: "Для размещения вакансий, поиска сотрудников и управления процессами.",
    disclaimer: "Вы не можете быть одновременно соискателем и работодателем с одной учетной записью.",
    davomEtish: "Продолжить",
    hasAccount: "Уже есть аккаунт?",
    noAccount: "Нет аккаунта?",
    adminConnect: "Связаться с админом",
    
    // Step 1 Profile Info
    profileInfoTitle: "Данные профиля",
    profileInfoSubtitle: "Введите основную информацию о себе",
    step1: "Профиль",
    step2: "Документы",
    step3: "Завершение",
    uploadPhoto: "Фото профиля (необязательно)",
    name: "ИМЯ *",
    surname: "ФАМИЛИЯ *",
    birthdate: "ДАТА РОЖДЕНИЯ *",
    day: "День",
    month: "Месяц",
    year: "Год",
    gender: "ПОЛ *",
    male: "Мужчина",
    female: "Женщина",
    email: "EMAIL (НЕОБЯЗАТЕЛЬНО)",

    // Step 2 Documents
    docTitle: "Загрузка документов",
    docSubtitle: "Подтвердите вашу личность и квалификацию",
    docWorkerPassport: "Копия паспорта или ID-карты *",
    docWorkerPassportDesc: "Загрузите в формате изображения (JPG, PNG) или PDF",
    docWorkerResume: "Резюме (CV) (необязательно)",
    docWorkerResumeDesc: "Предыдущее резюме или подробная информация",
    docEmployerLicense: "Лицензия / Свидетельство компании *",
    docEmployerLicenseDesc: "Разрешение на предпринимательскую деятельность",
    docEmployerLogo: "Логотип организации (необязательно)",
    docEmployerLogoDesc: "Официальный логотип для вашего бренда",
    uploadBtn: "Загрузить файл",
    uploaded: "Загружено",
    dragDropText: "Выберите файл или перетащите его сюда",
    demoDocText: "Заполнить демо-файлом",
    
    // Custom High-Fidelity Step 2 Keys
    identityTitle: "Подтверждение личности",
    identitySubtitle: "Введите паспортные данные. Все данные защищены.",
    series: "Серия",
    passportNumber: "Номер паспорта",
    jshshir: "ПИНФЛ (14 цифр)",
    passportFront: "Лицевая сторона *",
    passportBack: "Обратная сторона *",
    selfie: "Селфи фото *",
    selfieSubtitle: "Прямо, четко, лицо должно быть видно",
    sslNotice: "Все документы защищены SSL-шифрованием.",
    employerTitle: "Подтверждение организации",
    employerSubtitle: "Введите данные юридического лица. Все данные защищены.",
    orgName: "Название организации *",
    stir: "ИНН (9 цифр) *",
    license: "Лицензия / Свидетельство *",
    logo: "Логотип организации (необязательно)",
    submitVerify: "Подтвердить и продолжить",

    // Step 3 Finish
    finishTitle: "Активация аккаунта",
    finishSubtitle: "Установите учетные данные для входа в систему",
    finishPhone: "НОМЕР ТЕЛЕФОНА *",
    finishPassword: "СОЗДАЙТЕ ПАРОЛЬ *",
    finishConfirmPassword: "ПОДТВЕРДИТЕ ПАРОЛЬ *",
    finishAgree: "Я согласен с условиями использования и политикой конфиденциальности",
    errorPasswordMatch: "Пароли не совпадают",
    errorTerms: "Пожалуйста, примите условия использования",
    finishSuccess: "Регистрация успешно завершена!",
    finishButton: "Завершить и войти",
    
    // Login Screen
    phoneLabel: "НОМЕР ТЕЛЕФОНА *",
    passwordLabel: "ПАРОЛЬ *",
    loginBtn: "Войти",
    errorRequired: "Пожалуйста, заполните все обязательные поля",
    phonePlaceholder: "+998 (90) 123-45-67",
    passwordPlaceholder: "Введите пароль"
  },
  en: {
    regTitle: "Registration",
    loginTitle: "Log In",
    roleQuestion: "Who will you continue as?",
    roleSubtitle: "Select your role, it cannot be changed later",
    ishchi: "Job Seeker",
    ishchiDesc: "To search for jobs, create resumes and apply for vacancies.",
    ishBeruvchi: "Employer",
    ishBeruvchiDesc: "To post job openings, find candidates and manage workflows.",
    disclaimer: "You cannot be both a job seeker and an employer at the same time with one account.",
    davomEtish: "Continue",
    hasAccount: "Have an account?",
    noAccount: "Don't have an account?",
    adminConnect: "Contact Support",
    
    // Step 1 Profile Info
    profileInfoTitle: "Profile Details",
    profileInfoSubtitle: "Enter your basic information",
    step1: "Profile",
    step2: "Documents",
    step3: "Finish",
    uploadPhoto: "Profile picture (optional)",
    name: "FIRST NAME *",
    surname: "LAST NAME *",
    birthdate: "DATE OF BIRTH *",
    day: "Day",
    month: "Month",
    year: "Year",
    gender: "GENDER *",
    male: "Male",
    female: "Female",
    email: "EMAIL (OPTIONAL)",

    // Step 2 Documents
    docTitle: "Upload Documents",
    docSubtitle: "Confirm your identity and qualifications",
    docWorkerPassport: "Passport or ID Card Copy *",
    docWorkerPassportDesc: "Upload as image (JPG, PNG) or PDF format",
    docWorkerResume: "Resume (CV) (optional)",
    docWorkerResumeDesc: "Previous resume or detailed description",
    docEmployerLicense: "Company License / Certificate *",
    docEmployerLicenseDesc: "Business operation permit copy",
    docEmployerLogo: "Organization Logo (optional)",
    docEmployerLogoDesc: "Official brand identity icon",
    uploadBtn: "Upload File",
    uploaded: "Uploaded",
    dragDropText: "Choose file or drag and drop it here",
    demoDocText: "Autofill with sample file",
    
    // Custom High-Fidelity Step 2 Keys
    identityTitle: "Identity Verification",
    identitySubtitle: "Please enter your passport details. All data is secure.",
    series: "Series",
    passportNumber: "Passport Number",
    jshshir: "JSHSHIR (14 digits)",
    passportFront: "Front Side *",
    passportBack: "Back Side *",
    selfie: "Selfie Photo *",
    selfieSubtitle: "Straight, clear, face must be fully visible",
    sslNotice: "All documents are secured with SSL encryption.",
    employerTitle: "Organization Verification",
    employerSubtitle: "Enter legal entity details. All data is secure.",
    orgName: "Organization Name *",
    stir: "STIR (INN - 9 digits) *",
    license: "License / Certificate *",
    logo: "Organization Logo (optional)",
    submitVerify: "Verify & Continue",

    // Step 3 Finish
    finishTitle: "Activate Account",
    finishSubtitle: "Set up security credentials to access your account",
    finishPhone: "PHONE NUMBER *",
    finishPassword: "CREATE PASSWORD *",
    finishConfirmPassword: "CONFIRM PASSWORD *",
    finishAgree: "I agree to the terms of use and privacy policy",
    errorPasswordMatch: "Passwords do not match",
    errorTerms: "Please accept the terms and conditions",
    finishSuccess: "Successfully registered!",
    finishButton: "Finish & Enter",
    
    // Login Screen
    phoneLabel: "PHONE NUMBER *",
    passwordLabel: "PASSWORD *",
    loginBtn: "Log In",
    errorRequired: "Please fill in all required fields",
    phonePlaceholder: "+998 (90) 123-45-67",
    passwordPlaceholder: "Enter your password"
  }
};

export const MONTHS = {
  uz: ['Yanvar', 'Fevral', 'Mart', 'Aprel', 'May', 'Iyun', 'Iyul', 'Avgust', 'Sentabr', 'Oktabr', 'Noyabr', 'Dekabr'],
  ru: ['Январь', 'Февраль', 'Март', 'Апрель', 'Май', 'Июнь', 'Июль', 'Август', 'Сентябрь', 'Октябрь', 'Ноябрь', 'Декабрь'],
  en: ['January', 'February', 'March', 'April', 'May', 'June', 'July', 'August', 'September', 'October', 'November', 'December']
};

export const AVATAR_PRESETS = [
  'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=120&h=120&q=80',
  'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=120&h=120&q=80',
  'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=120&h=120&q=80',
  'https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?auto=format&fit=crop&w=120&h=120&q=80',
  'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=120&h=120&q=80'
];
