import { Job, Chat } from './types';
import { realNewJobs } from './data/realNewJobs';
import { samarqandJobs } from './data/samarqandJobs';
import { buxoroJobs } from './data/buxoroJobs';
import { ferganaJobs } from './data/ferganaJobs';
import { andijonJobs } from './data/andijonJobs';
import { namanganJobs } from './data/namanganJobs';
import { southernJobs } from './data/southernJobs';
import { centralJobs } from './data/centralJobs';
import { westernJobs } from './data/westernJobs';
import { allGeneratedJobs } from './data/jobGenerator';

const allInitialJobsRaw: Job[] = [
  ...realNewJobs,
  {
    id: '2',
    title: 'Uy ko\'chirishga yuk tashuvchi',
    company: 'Yuk tashish xizmati',
    logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "180 000 so'm",
    tags: ["5 soatlik", "Yengil yuk"],
    location: 'Toshkent, Chilonzor',
    coordinates: { x: 35, y: 48 },
    time: '2026-07-05',
    urgent: false,
    applied: true,
    bookmarked: false,
    status: 'applied',
    description: 'Chilonzor 3-mavzedagi 4-qavatdan mebel va kiyimlarni pastga tushirib, yuk mashinasiga yuklash kerak. Lift yo\'q, lekin yuklar og\'ir emas (asosan qutilar va yengil jihozlar). 3 kishi kerak.',
    hourlyRate: "36 000",
    transportRate: "Yo'q",
    periodText: "2026-07-12 13:00~18:00",
    durationLabel: "5 soatlik"
  },
  {
    id: '3',
    title: 'Vagondan sement qoplarni tushirish',
    company: 'Qurilish Materiallari Ombori',
    logoUrl: 'https://images.unsplash.com/photo-1516594798947-e65505dbb29d?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "450 000 so'm",
    tags: ["1 kunlik", "Jismoniy og'ir"],
    location: 'Toshkent, Sergeli',
    coordinates: { x: 55, y: 72 },
    time: '2026-07-01',
    urgent: true,
    applied: false,
    bookmarked: false,
    status: 'todo',
    description: 'Sergeli yuk stansiyasida vagondan 50 kg lik sement qoplarini omborga tushirish kerak. Jismoniy baquvvat, ishchan yigitlar qidirilmoqda. Tushlik va kechki ovqat bepul tashkil etiladi.',
    hourlyRate: "45 000",
    transportRate: "20 000",
    periodText: "2026-07-10 09:00~19:00",
    durationLabel: "1 kunlik"
  },
  {
    id: '4',
    title: 'Issiqxonada pomidor terish',
    company: 'Agro-Firma Qibray',
    logoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "150 000 so'm / kunlik",
    tags: ["3 kunlik", "Oson ish"],
    location: 'Toshkent vil., Qibray',
    coordinates: { x: 62, y: 32 },
    time: '2026-07-19',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'confirmed',
    description: 'Qibray tumanidagi issiqxonadan pishgan pomidorlarni terish va qutilarga saralash ishi. Qizlar va ayollar uchun ham juda mos. Maxsus transport Yunusobod metrosidan olib ketadi va qaytaradi.',
    hourlyRate: "18 000",
    transportRate: "Bepul avtobus",
    periodText: "2026-07-05~07 08:00~16:00",
    durationLabel: "3 kunlik"
  },
  {
    id: '5',
    title: 'Hovli tozalash va daraxt butash',
    company: 'Xususiy xonadon egasi',
    logoUrl: 'https://images.unsplash.com/photo-1464226184884-fa280b87c39e?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "200 000 so'm",
    tags: ["6 soatlik", "Asboblar bor"],
    location: 'Toshkent, Mirzo Ulug\'bek',
    coordinates: { x: 28, y: 56 },
    time: '2026-07-19',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'confirmed',
    description: 'Katta hovlidagi begona o\'tlarni yulish, daraxt shoxlarini kesish va butalgan shox-shabbalarni yuk mashinasiga ortish kerak. Barcha zaruriy asbob-uskunalar (arra, qaychi, qo\'lqoplar) yetkazib beriladi.',
    hourlyRate: "33 000",
    transportRate: "Yo'q",
    periodText: "2026-07-09 09:00~15:00",
    durationLabel: "6 soatlik"
  },
  {
    id: '6',
    title: 'Mebel qismlarini yig\'ish yordamchisi',
    company: 'Mebel master',
    logoUrl: 'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "220 000 so'm / kunlik",
    tags: ["2 kunlik", "Yengil usta"],
    location: 'Toshkent, Uchtepa',
    coordinates: { x: 40, y: 60 },
    time: '2026-07-06',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'completed',
    description: 'Yangi tayyorlangan shkaflar va oshxona mebellarinin detal qismlarini ko\'tarib turish, murvatlarni burashga yordam berish kerak. Tajribali usta boshchiligida ishlanadi. Shogird tushish niyatidagilar uchun qulay imkoniyat.',
    hourlyRate: "24 000",
    transportRate: "15 000",
    periodText: "2026-07-01~02 08:00~17:00",
    durationLabel: "2 kunlik"
  },
  {
    id: '7',
    title: 'Ariq qazish va kabel yotqizish',
    company: 'Energo-Montaj',
    logoUrl: 'https://images.unsplash.com/photo-1541888946425-d81bb19240f5?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "1 200 000 so'm",
    tags: ["5 kunlik", "Asboblar bor"],
    location: 'Toshkent, Bektemir',
    coordinates: { x: 65, y: 28 },
    time: '2026-07-08',
    urgent: true,
    applied: false,
    bookmarked: false,
    status: 'completed',
    description: 'Katta ko\'cha bo\'ylab optik tolali kabel yotqizish uchun 60 sm chuqurlikda ariq qazish ishi. Ketmon va kuraklar bilan ta\'minlanadi. Kunlik tushlik va ovqatlanish tashkil etiladi, yakuniy hisob-kitob 5-kuni to\'liq beriladi.',
    hourlyRate: "24 000",
    transportRate: "Yo'l xarajati bor",
    periodText: "2026-07-01~05 08:00~18:00",
    durationLabel: "5 kunlik"
  },
  {
    id: '8',
    title: 'To\'yxonada idish va stol yig\'ish',
    company: 'Visol To\'yxonasi',
    logoUrl: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "160 000 so'm",
    tags: ["8 soatlik", "Tungi smena"],
    location: 'Toshkent, Olmazor',
    coordinates: { x: 70, y: 20 },
    time: '2026-07-14',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'completed',
    description: 'Kechki to\'y marosimi tugagandan so\'ng stol ustidagi idishlarni, dasturxonlarni va stullarni tartibga keltirib yig\'ishtirish. To\'yxona ma\'muriyati tomonidan kechki ovqat hamda uyingizga qaytish uchun taksi xizmati bepul tashkil etiladi.',
    hourlyRate: "20 000",
    transportRate: "Taksi kafolatlangan",
    periodText: "2026-07-01 20:00~04:00",
    durationLabel: "8 soatlik"
  },
  {
    id: '9',
    title: 'Restoranda idish-tovoq yuvishga yordamchi',
    company: 'Milliy Taomlar',
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "180 000 so'm / kunlik",
    tags: ["1 haftalik", "Issiq ovqat"],
    location: 'Toshkent, Yashnobod',
    coordinates: { x: 78, y: 45 },
    time: '2026-07-13',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'completed',
    description: 'Chorshanba-yakshanba kunlari o\'rtasidagi eng gavjum vaqtlarda oshxonada idish yuvuvchi opaga yordamchi kerak. Toza, ozoda va harakatchan bo\'lish shart. Kuniga 2 mahal issiq ovqat va choy doimo bor.',
    hourlyRate: "18 000",
    transportRate: "10 000",
    periodText: "2026-07-01~07 11:00~21:00",
    durationLabel: "1 haftalik"
  },
  {
    id: '10',
    title: 'Bog\'da gilos va o\'rik terish',
    company: 'Parkent Bog\'dorchilik',
    logoUrl: 'https://images.unsplash.com/photo-1534447677768-be436bb09401?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "140 000 so'm / kunlik",
    tags: ["1 haftalik", "Mavsumiy"],
    location: 'Toshkent vil., Parkent',
    coordinates: { x: 26, y: 64 },
    time: '2026-07-08',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'completed',
    description: 'Parkent tumanidagi bog\'lardan gilos va o\'rik mevalarini terib, yashiklarga joylashtirish kerak. Ish haqi har kuni kechqurun naqd beriladi. Yotoqxona va 3 mahal ovqat bepul kafolatlanadi.',
    hourlyRate: "16 000",
    transportRate: "Yotoqxona + Ovqat",
    periodText: "2026-07-01~07 07:00~16:00",
    durationLabel: "1 haftalik"
  },
  {
    id: '11',
    title: "Restoranda mijozlarga xizmat ko'rsatish",
    company: "Oasis Cafe & Lounge",
    logoUrl: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "200 000 so'm / kunlik",
    tags: ["3 kunlik", "Moslashuvchan"],
    location: "Toshkent, Mirobod",
    coordinates: { x: 74, y: 38 },
    time: '2026-07-14',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'todo',
    description: "Mirobod tumanidagi shinam kafega dam olish kunlarida mijozlarni kutib olish va buyurtmalarni yetkazish uchun chaqqon yordamchi kerak. Toza va ozoda kiyinish, xushmuomalalik talab etiladi.",
    hourlyRate: "25 000",
    transportRate: "Bepul tushlik",
    periodText: "2026-07-11 12:00~22:00",
    durationLabel: "3 kunlik"
  },
  {
    id: '12',
    title: "Brend do'konida kiyimlar taqsimoti",
    company: "Glamour Boutiques",
    logoUrl: 'https://images.unsplash.com/photo-1441986300917-64674bd600d8?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "180 000 so'm / kunlik",
    tags: ["2 kunlik", "Yengil ish"],
    location: "Toshkent, Shayxontohur",
    coordinates: { x: 42, y: 35 },
    time: '2026-07-19',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Yangi kelgan kiyim-kechak partiyasini qutilardan ochish, maxsus osgichlarga ilish va vitrinaga chiroyli qilib joylashtirish ishi. Ish oson va bino ichida, konditsioner ostida bajariladi.",
    hourlyRate: "22 500",
    transportRate: "Yo'q",
    periodText: "2026-07-10~11 10:00~18:00",
    durationLabel: "2 kunlik"
  },
  {
    id: '13',
    title: "Ofisni tozalash va tartibga keltirish",
    company: "CleanPro Co.",
    logoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "150 000 so'm",
    tags: ["4 soatlik", "Asboblar bor"],
    location: "Toshkent, Yakkasaroy",
    coordinates: { x: 48, y: 52 },
    time: '2026-07-15',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Yakkasaroy tumanidagi kichik IT ofisini kechqurun tozalash, pollarni yuvish va chiqindilarni olib chiqish kerak. Tozalash vositalari va jihozlari ofisda mavjud.",
    hourlyRate: "37 500",
    transportRate: "Yo'l xarajati bor",
    periodText: "2026-07-09 18:00~22:00",
    durationLabel: "4 soatlik"
  },
  {
    id: '14',
    title: "Supermarketda mahsulotlarni joylash",
    company: "Makro Supermarket",
    logoUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "170 000 so'm / kunlik",
    tags: ["3 kunlik", "Tushlik bor"],
    location: "Toshkent, Yangihayot",
    coordinates: { x: 50, y: 78 },
    time: '2026-07-05',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Yangihayot tumanidagi yangi ochilayotgan Makro filialida oziq-ovqat mahsulotlarini peshtaxtalarga yorliqlari bo'yicha chiroyli joylashtirib chiqish kerak. Tajriba shart emas.",
    hourlyRate: "21 000",
    transportRate: "Tushlik va kiyim bepul",
    periodText: "2026-07-11~13 09:00~17:00",
    durationLabel: "3 kunlik"
  },
  {
    id: '15',
    title: "Baliqchilik xo'jaligida baliq ovlash",
    company: "Chinoz Baliq Xolding",
    logoUrl: 'https://images.unsplash.com/photo-1511497584788-876760111969?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "220 000 so'm / kunlik",
    tags: ["2 kunlik", "Mavsumiy"],
    location: "Toshkent vil., Chinoz",
    coordinates: { x: 15, y: 85 },
    time: '2026-07-12',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Chinoz tumanidagi sun'iy ko'llardan tayyor baliqlarni to'r bilan suzib olish va maxsus muzlatkichli idishlarga joylashtirish. Jismonan faol va g'ayratli yigitlar qidirilmoqda.",
    hourlyRate: "27 500",
    transportRate: "Transport bor",
    periodText: "2026-07-10~11 06:00~14:00",
    durationLabel: "2 kunlik"
  },
  {
    id: '16',
    title: "Dala shiyponida sug'orish yordamchisi",
    company: "Chirchiq Agro klaster",
    logoUrl: 'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "250 000 so'm / kunlik",
    tags: ["5 kunlik", "Yotoqxona bor"],
    location: "Toshkent vil., Quyi Chirchiq",
    coordinates: { x: 22, y: 78 },
    time: '2026-07-15',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Quyi Chirchiq tumanidagi g'alla va paxta dalalarini reja asosida sug'orishda mirshabga yordam berish. Barcha sharoitlar dala shiyponida yaratilgan, 3 mahal issiq ovqat bepul.",
    hourlyRate: "31 000",
    transportRate: "Yotoqxona + Ovqat bepul",
    periodText: "2026-07-12~16 08:00~16:00",
    durationLabel: "5 kunlik"
  },
  {
    id: '17',
    title: "G'isht zavodida mahsulotlarni saralash",
    company: "Yangiyo'l G'isht Invest",
    logoUrl: 'https://images.unsplash.com/photo-1590069261209-f8e9b8642343?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "300 000 so'm / kunlik",
    tags: ["3 kunlik", "Og'ir ish"],
    location: "Toshkent vil., Yangiyo'l",
    coordinates: { x: 44, y: 76 },
    time: '2026-07-03',
    urgent: true,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Pishgan g'ishtlarni pechdan tushirish, sifatini tekshirib paletkalarga chiroyli taxlash ishi. Qo'lqop va maxsus kiyimlar zavod tomonidan beriladi. Tushlik bepul.",
    hourlyRate: "37 500",
    transportRate: "Yo'q",
    periodText: "2026-07-10~12 08:00~16:00",
    durationLabel: "3 kunlik"
  },
  {
    id: '18',
    title: "Olma bog'ida hosilni yig'ish",
    company: "Bo'stonliq Bog'lari",
    logoUrl: 'https://images.unsplash.com/photo-1619546813926-a78fa6372cd2?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "180 000 so'm / kunlik",
    tags: ["4 kunlik", "Oson ish"],
    location: "Toshkent vil., Bo'stonliq",
    coordinates: { x: 75, y: 15 },
    time: '2026-07-02',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Chorvoq suv ombori yaqinidagi olma bog'laridan pishgan olmalarni ehtiyotkorlik bilan uzib, yashiklarga qadoqlash. Transport va tushlik bepul tashkil etilgan.",
    hourlyRate: "22 500",
    transportRate: "Chilonzordan bepul avtobus",
    periodText: "2026-07-11~14 08:00~16:00",
    durationLabel: "4 kunlik"
  },
  {
    id: '19',
    title: "Avtoyuvish shoxobchasida yordamchi",
    company: "Zangiota Auto Clean",
    logoUrl: 'https://images.unsplash.com/photo-1607860108855-64acf2078ed9?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "200 000 so'm",
    tags: ["1 kunlik", "Foiz ham bor"],
    location: "Toshkent vil., Zangiota",
    coordinates: { x: 45, y: 62 },
    time: '2026-07-13',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Zangiota tumanidagi gavjum avtoyuvish shoxobchasiga bir kunga chaqqon yordamchi kerak. Mashinalar salonini changyutgich qilish va oynalarini quritib artish ishlari topshiriladi.",
    hourlyRate: "25 000",
    transportRate: "Tushlik beriladi",
    periodText: "2026-07-10 09:00~17:00",
    durationLabel: "1 kunlik"
  },
  {
    id: '20',
    title: "Gilam yuvish sexida ishchi",
    company: "Nurafshon Clean",
    logoUrl: 'https://images.unsplash.com/photo-1527515637462-cff94eecc1ac?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "230 000 so'm / kunlik",
    tags: ["3 kunlik", "Yotoq bor"],
    location: "Toshkent vil., O'rtachirchiq",
    coordinates: { x: 58, y: 55 },
    time: '2026-07-15',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Gilamlarni maxsus uskunalar yordamida yuvish, siqish va quritish xonalariga osish ishiga chaqqon yigitlar kerak. O'rganish oson, birinchi kuni o'rgatiladi.",
    hourlyRate: "28 750",
    transportRate: "Tushlik bor",
    periodText: "2026-07-10~12 08:00~16:00",
    durationLabel: "3 kunlik"
  },
  {
    id: '21',
    title: "Qurilish materiallarini yuklash",
    company: "Ohangaron Sement Depot",
    logoUrl: 'https://images.unsplash.com/photo-1504307651254-35680f356dfd?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "280 000 so'm / kunlik",
    tags: ["2 kunlik", "Jismoniy ish"],
    location: "Toshkent vil., Ohangaron",
    coordinates: { x: 80, y: 70 },
    time: '2026-07-17',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Ohangarondagi ulgurji omborda tayyor qurilish qorishmalari va quruq sement qoplarini yuk mashinalariga ortish. Jismoniy baquvvat yoshlar taklif etiladi.",
    hourlyRate: "35 000",
    transportRate: "Tushlik va yo'lkira bor",
    periodText: "2026-07-10~11 08:00~16:00",
    durationLabel: "2 kunlik"
  },
  {
    id: '22',
    title: "Ziyoratgoh atrofini obodonlashtirish",
    company: "Samarqand Obodlik",
    logoUrl: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "250 000 so'm",
    tags: ["1 kunlik", "Milliy qadriyat"],
    location: "Samarqand viloyati",
    coordinates: { x: 50, y: 50 },
    time: '2026-07-18',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Samarqand shahridagi tarixiy maqbara atrofidagi xiyobonni begona o'tlardan tozalash, daraxtlarni oqlash va gullarni sug'orish ishlari. Tushlik milliy taomlar bepul.",
    hourlyRate: "31 250",
    transportRate: "Yo'l xarajati bepul",
    periodText: "2026-07-11 08:00~16:00",
    durationLabel: "1 kunlik"
  },
  {
    id: '23',
    title: "Tarixiy obida hovlisini tozalash",
    company: "Buxoro Heritage",
    logoUrl: 'https://images.unsplash.com/photo-1518391846015-55a9cc003b25?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "220 000 so'm / kunlik",
    tags: ["2 kunlik", "Madaniy meros"],
    location: "Buxoro viloyati",
    coordinates: { x: 50, y: 50 },
    time: '2026-07-13',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Eski Buxoro hududidagi karvonsaroy hovlisini chang-g'uborlardan tozalash, supurib-sidirish ishi. Sayyohlar ko'p keladigan joy bo'lganligi sababli ozodalikka katta e'tibor beriladi.",
    hourlyRate: "27 500",
    transportRate: "Tushlik va kiyim beriladi",
    periodText: "2026-07-10~11 08:00~16:00",
    durationLabel: "2 kunlik"
  },
  {
    id: '24',
    title: "Buxoro mehmonxonasi yordamchi xodimi",
    company: "Grand Bukhara Hotel",
    logoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "180 000 so'm / kunlik",
    tags: ["Kunduzgi", "Xizmat ko'rsatish"],
    location: "Buxoro, Buxoro shahri",
    coordinates: { x: 48, y: 52 },
    time: '2026-07-04',
    urgent: true,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Mehmonlarni kutib olishda ko'maklashish, yuklarni tashish va xonalarni tayyorlashda yordam berish.",
    hourlyRate: "22 500",
    transportRate: "Tushlik kompaniya hisobidan",
    periodText: "2026-07-09 09:00~17:00",
    durationLabel: "1 kunlik"
  },
  {
    id: '25',
    title: "Registon maydoni promo-tarqatuvchi",
    company: "Samarqand Travel",
    logoUrl: 'https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "150 000 so'm / kunlik",
    tags: ["4 soatlik", "Marketing"],
    location: "Samarqand, Samarqand shahri",
    coordinates: { x: 52, y: 48 },
    time: '2026-07-12',
    urgent: false,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Tarixiy maydon atrofida sayyohlarga bukletlar va tarqatma materiallar ulashish.",
    hourlyRate: "37 500",
    transportRate: "Yo'l xarajati bepul",
    periodText: "2026-07-09 10:00~14:00",
    durationLabel: "Yarim kun"
  },
  {
    id: '26',
    title: "Andijon bozori yuk tashuvchisi",
    company: "Vodiy savdo",
    logoUrl: 'https://images.unsplash.com/photo-1473448912268-2022ce9509d8?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    salary: "300 000 so'm / kunlik",
    tags: ["Kunlik", "Og'ir mehnat"],
    location: "Andijon, Andijon shahri",
    coordinates: { x: 50, y: 50 },
    time: '2026-07-12',
    urgent: true,
    applied: false,
    bookmarked: false,
    status: 'none',
    description: "Ombordan do'konlarga yuklarni xavfsiz va tezkorlik bilan yetkazib berish va joylashtirish.",
    hourlyRate: "37 500",
    transportRate: "Bepul tushlik beriladi",
    periodText: "2026-07-09 08:00~16:00",
    durationLabel: "1 kunlik"
  },
  ...samarqandJobs,
  ...allGeneratedJobs
];

export const initialJobs: Job[] = allInitialJobsRaw.slice(0, 10);

export const initialChats: Chat[] = [
  {
    id: 'c1',
    companyName: 'Artel Mebel Sexi',
    logoUrl: 'https://images.unsplash.com/photo-1556911220-e15b29be8c8f?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    recruiterName: 'Malika Axmedova',
    recruiterAvatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    online: true,
    unreadCount: 1,
    lastMessageTime: '14:30',
    messages: [
      {
        id: '1',
        sender: 'recruiter',
        text: 'Assalomu alaykum! Bizga bugun mebel sexiga shoshilinch ravishda 1 kunlik yordamchi usta kerak edi. Kunlik ish haqi 200 000 so\'m naqd beriladi, tushlik va choy bizning hisobimizdan.',
        time: '2026-07-16'
      },
      {
        id: '2',
        sender: 'user',
        text: 'Vaalaykum assalom! Taklif uchun katta rahmat. Men tayyorman, asboblar o\'zim bilan bo\'lishi kerakmi va manzil aynan qayerda?',
        time: '2026-07-11'
      },
      {
        id: '3',
        sender: 'recruiter',
        text: 'Yo\'q, barcha asbob-uskunalar sexda bor. Manzil: Toshkent sh., Bektemir tumani, Artel zavodi yaqinidagi mebel sexi. Kelishingiz bilan ishlarni tushuntiramiz.',
        time: '2026-07-06',
        hasMap: true,
        mapLocation: 'Tashkent, Bektemir'
      },
      {
        id: '4',
        sender: 'user',
        text: 'Ajoyib, tushunarli. Men dushanba kuni ertalab soat 08:30 ga yetib boraman.',
        time: '2026-07-13'
      },
      {
        id: '5',
        sender: 'recruiter',
        text: 'Kelishdik, sizni kutamiz! Kelishda shaxsingizni tasdiqlovchi hujjat (pasport yoki ID karta) olib kelishni unutmang.',
        time: '2026-07-01'
      }
    ]
  },
  {
    id: 'c2',
    companyName: 'Korzinka Chilonzor',
    logoUrl: 'https://images.unsplash.com/photo-1560179707-f14e90ef3623?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    recruiterName: 'Sardor Karimov',
    recruiterAvatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    online: true,
    unreadCount: 2,
    lastMessageTime: '11:15',
    messages: [
      {
        id: '1',
        sender: 'user',
        text: 'Assalomu alaykum! Chilonzor filialidagi bugungi 4 soatlik tungi yuk joylashtiruvchi (merchandiser) buyurtmasi bo\'yicha ishlamoqchi edim, bugun borib ishni boshlasam bo\'ladimi?',
        time: '2026-07-04'
      },
      {
        id: '2',
        sender: 'recruiter',
        text: 'Vaalaykum assalom. Ha, albatta. Bugun soat 14:00 dan 17:00 gacha kelsangiz, tezda shartlarni tushuntirib, yo\'llanma beramiz. Soatbay to\'lov 30 000 so\'mdan, kunlik ish tugashi bilan hisob-kitob qilinadi.',
        time: '2026-07-14'
      },
      {
        id: '3',
        sender: 'recruiter',
        text: 'Yashnobod tumanidagi bosh ofisimizga kelasiz. Metro \'Do\'stlik\' bekati yaqinida joylashgan. Kelganda Sardor deb so\'rang, yo\'llanmangizni beraman.',
        time: '2026-07-11'
      }
    ]
  },
  {
    id: 'c3',
    companyName: 'Qibray Agro-Issiqxona',
    logoUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    recruiterName: 'Zuhra Karimboyeva',
    recruiterAvatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    online: false,
    unreadCount: 0,
    lastMessageTime: 'Kecha',
    messages: [
      {
        id: '1',
        sender: 'recruiter',
        text: 'Assalomu alaykum, Qibrayda pomidor terish bo\'yicha kunlik mavsumiy ishga so\'ragandingiz. Ertadan yangi guruhimiz dalaga chiqadi. Kunlik tushlik va transport mutlaqo bepul.',
        time: '2026-07-18'
      },
      {
        id: '2',
        sender: 'user',
        text: 'Vaalaykum assalom! Ha, men tayyorman. Kunlik ish haqi qancha va maxsus avtobus qayerdan soat nechada ketadi?',
        time: '2026-07-18'
      },
      {
        id: '3',
        sender: 'recruiter',
        text: 'Kunlik to\'lov har kuni kechqurun 150 000 so\'mdan naqd yoki kartaga o\'tkazib beriladi. Avtobusimiz Yunusobod metrosi chiqishidagi avtoturargohdan 07:30 da yo\'lga chiqadi.',
        time: '2026-07-03'
      },
      {
        id: '4',
        sender: 'user',
        text: 'Tushunarli. Ertaga 07:15 da o\'sha yerda bo\'laman. Katta rahmat, kechikmayman!',
        time: '2026-07-12'
      }
    ]
  },
  {
    id: 'c4',
    companyName: 'Visol To\'yxonasi',
    logoUrl: 'https://images.unsplash.com/photo-1554415707-6e8cfc93fe23?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    recruiterName: 'Anvar Shodiyev',
    recruiterAvatar: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    online: true,
    unreadCount: 0,
    lastMessageTime: 'Kecha',
    messages: [
      {
        id: '1',
        sender: 'recruiter',
        text: 'Uka, bugun kechqurun soat 20:00 da boshlanadigan marosim uchun idish va stol yig\'ishga qo\'shimcha yordamchi kerak edi. Kunlik to\'lov 160 000 so\'m naqd beriladi.',
        time: '2026-07-16'
      },
      {
        id: '2',
        sender: 'user',
        text: 'Assalomu alaykum, Anvar aka! Men tayyorman, bemalol chiqa olaman. To\'yxona qaysi hududda joylashgan?',
        time: '2026-07-12'
      },
      {
        id: '3',
        sender: 'recruiter',
        text: 'Olmazor tumani, Beruniy metro bekatiga yaqin. To\'y tugagach, uyingizga qaytish uchun taksi xizmati bepul kafolatlanadi.',
        time: '2026-07-16'
      },
      {
        id: '4',
        sender: 'user',
        text: 'Juda yaxshi, unda soat 19:45 ga to\'yxona oldiga yetib boraman.',
        time: '2026-07-19'
      }
    ]
  },
  {
    id: 'c5',
    companyName: 'Yunusobod Yuk Xizmati',
    logoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    recruiterName: 'Sirojiddin Aliyev',
    recruiterAvatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    online: false,
    unreadCount: 0,
    lastMessageTime: '2 kun oldin',
    messages: [
      {
        id: '1',
        sender: 'recruiter',
        text: 'Assalomu alaykum. Shahar ichida ofis ko\'chirish xizmati uchun vaqtinchalik yuk tashuvchi lavozimiga qiziqish bildirgan ekansiz. Jismoniy yuk tashishda tajribangiz bormi?',
        time: '2026-07-13'
      },
      {
        id: '2',
        sender: 'user',
        text: 'Vaalaykum assalom. Jismoniy baquvvatman, avval ham bir necha bor uy va ofis ko\'chirish ishlarida ishtirok etganman. Kunlik to\'lov qancha bo\'ladi?',
        time: '2026-07-17'
      },
      {
        id: '3',
        sender: 'recruiter',
        text: 'Ish dushanba kuni soat 09:00 dan 16:00 gacha davom etadi. Kunlik to\'lov 180 000 so\'m naqd. Ma\'lumotlaringizni tizimga kiritdim, dushanba kuni aloqaga chiqamiz.',
        time: '2026-07-07'
      }
    ]
  },
  {
    id: 'c6',
    companyName: 'Grand To\'yxona',
    logoUrl: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    recruiterName: 'Feruza Jalilova',
    recruiterAvatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=100&auto=format&fit=crop&q=60&ixlib=rb-4.0.3',
    online: false,
    unreadCount: 0,
    lastMessageTime: '3 kun oldin',
    messages: [
      {
        id: '1',
        sender: 'recruiter',
        text: 'Xush kelibsiz! Yakshanba kungi katta konferensiyada mehmonlarni kutib olish va tushlik zalida yordamlashish uchun 1 kunlik yordamchi xodim kerak. Kunlik haq 220 000 so\'m.',
        time: '2026-07-15'
      },
      {
        id: '2',
        sender: 'user',
        text: 'Assalomu alaykum, Feruza opa! Zo\'r taklif, men ishtirok eta olaman. Ish vaqti soat nechadan nechagacha davom etadi va kiyinish tartibi bormi?',
        time: '2026-07-02'
      },
      {
        id: '3',
        sender: 'recruiter',
        text: 'Ajoyib. Ish vaqti soat 09:00 dan 17:00 gacha. Kiyinish klassik uslubda (oq ko\'ylak, qora shim). Ertaga kutib qolamiz!',
        time: '2026-07-15'
      }
    ]
  }
];
